# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Extractor
                                 A QGIS plugin
 Extraction tool to extract values from raster in many way
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-08
        copyright            : (C) 2023 by Stanislas Mahussi GANDAHO
        email                : gandahostanmah@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Extractor class from file Extractor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Extractor import Extractor
    return Extractor(iface)
